Task2 due date
JaegeonJo/react-typescript-practice pull request #3
Opened 2024-03-27 00:50 UTC by JaegeonJo

## Description
Todo Item에 due date를 설정할 수 있도록 하였습니다. 
- 오늘 이후의 날짜만 설정가능합니다.
- Todo List가 due date를 기준으로 정렬됩니다. 

마이너한 변경점은 아래와 같습니다. 
- 입력이 빈 칸인 상태에서 Add나 Update를 누를 경우 경고창을 띄우고 기능을 수행 하지 않습니다. 
- Todo list의 style을 수정하였습니다. 

## ScreenShot
![image](https://github.com/JaegeonJo/react-typescript-practice/assets/105850572/01bb93aa-efb0-4482-8a75-0754613d0fa9)

## 궁금한 점
- 권장되는 css 적용 방식
- 읽기 쉬운 코드를 작성하는 방법...

2024-03-27 01:41 UTC, limgit requested changes
전반적으로 코드에서 흠잡을건 없고, early-return 관련 코멘트는 취향의 영역에 가까우니 코드 가독성에 도움이 된다고 판단되는 경우에만 채용하는 것이 좋습니다.

일반적으로는 코드의 nesting을 줄이고, 코드 읽는 사람이 머릿속에서 가지를 하나씩 쳐나가는 식으로 읽을 수 있게 되다 보니 가독성이 오르긴 할겁니다.


근데 이 과제에서는 due date 설정하는 부분의 인풋을 `input type="date"`를 활용하지 말고, 직접 date picker를 만드는 식으로 구현하는걸 의도하긴 했습니다. 유저에게 텍스트 인풋까지 허용하는 date picker를 만들려면 각종 엣지 케이스 처리하느라 머리가 복잡할 테니 아래같은 구조의 date picker를 간단하게 하나 만들어보도록 합시다 (advanced 불릿은 구현하지 않고 넘어가도 괜찮습니다):

- date picker는 버튼으로 구성됩니다. 버튼의 레이블은 현재 선택된 날짜를 보여줍니다.
- 버튼을 클릭하면 아래쪽에 달력 div가 하나 붙습니다. 해당 div는 오늘을 기준으로 한 월간 달력을 보여주고 (i.e., 2024.03.27.에 달력을 열면 2024.03. 달력이 보입니다), 유저는 달력의 임의 날짜를 클릭하여 날짜를 선택할 수 있습니다. 유저가 날짜를 선택하면 달력 div는 사라지고 버튼의 현재 선택된 날짜가 해당 날짜로 업데이트 됩니다.
- 달력 div는 (당연히) 이전월/다음월 탐색이 가능해야 하고, 현재 보여지는 달력이 몇 년 몇 월의 것인지 유저에게 노출해야 합니다.
- date picker는 min date를 prop으로 받아서 min date 이전(exclusive)의 날짜를 선택할 수 없도록 막을 수 있어야 합니다. prop으로 min date가 주어지지 않는다면 모든 날짜를 선택할 수 있도록 해야합니다.
- (Advanced) 유저가 몇 년 몇 월을 표시하는 영역을 클릭할 수 있게 만들고, 그 영역을 클릭하면 달력 div가 연도 선택기 div로 바뀌도록 해봅시다. 연도 선택기 div는 2000년부터 2999년까지를 보여주고, 유저가 연도를 선택하면 해당 연도로 점프하며 달력 div를 보여주게 하면 됩니다.

대략 [이런 Date Picker](https://ant.design/components/date-picker)에서 1) 달력이 팝업으로 나오지 않고 그냥 normal div로 나오고, 2) date picker 버튼에 텍스트 입력이 허용되지 않는 버전을 만드는거라고 생각하시면 될 것 같습니다.

2024-03-27 01:41 UTC, limgit commented on src/App.tsx
> +              }
P4: 개인 취향의 영역이긴 한데, validation => main logic 형태를 갖는 코드에서 저는 early return 패턴을 사용해서 코드의 depth를 줄이는걸 선호하는 편입니다. 예를 들어 이 코드의 경우

```ts
if (userInput === "") {
  // Validation failed. Show error to user and early-return.
  window.alert("내용을 입력해주세요.");
  setUserInput(item.content);
  return;
}
// Validation passed. Main logic executed.
setUserInput(userInput);
onChangeContent(userInput);
setIsEdit(false);
```

의 형태가 되겠죠?

그리고 `setUserInput(userInput)` 은 의미 없는 라인으로 보이네요.

2024-03-27 01:41 UTC, limgit commented on src/App.tsx
> +            }
P4: 여기도 마찬가지로 early-return 패턴을 쓸 수 있습니다.

```ts
if (!isFuture(selectedDate)) {
  window.alert("오늘 날짜부터 선택 가능합니다.");
  return;
}
setInputDueDate(event.target.value);
```

2024-03-27 01:54 UTC, JaegeonJo commented on src/App.tsx
> +              }
분기 처리 하지 않는 부분이 main logic 이군요! 
https://github.com/JaegeonJo/react-typescript-practice/pull/3/commits/8c94ab7f9c0f1006ea5a36f258d4f3120b0e8993 에서 변경하였습니다.

2024-03-27 01:54 UTC, JaegeonJo commented on src/App.tsx
> +            }
Fixed in https://github.com/JaegeonJo/react-typescript-practice/pull/3/commits/8c94ab7f9c0f1006ea5a36f258d4f3120b0e8993 에서 변경하였습니다.

2024-03-27 01:58 UTC, limgit commented
"권장되는 css 적용 방법" 토픽은 이거만 가지고도 얘기할게 많은 주제라 여기서 서면으로 다 설명드리기는 곤란할 것 같고, 간단히만 이야기하자면

1. 가장 naive한 접근법은 React에서 기본으로 제공해주는 `style` prop을 이용하는 방법입니다. 이건 HTML 상에서 inline-style로 변환되어 적용되는데요, 일반적으로 inline styling은 각종 advanced CSS 기능을 사용할 수 없고, [React에서도 스타일이 JS 변수에 의존하는게 아니라면 지양하라고 언급](https://react.dev/reference/react-dom/components/common#usage) (We recommend only using the style attribute when your styles depend on JavaScript variables.) 하고 있기에 다른 방법을 쓰는게 좋습니다.
2. 그 다음으로 사용할 수 있는 방법은 `public` 디렉토리 아래에 `.css` 파일들을 만들고 그 안에 다양한 css class를 선언한 뒤 `index.html`에서 `style` 태그로 해당 css들을 임포트하고, React 내부에선 `className`을 이용해 클래스를 부여하여 스타일링 하는 방식이 있습니다. 이 방식은 가장 기초적으로 css 파일을 쓰는 방법인데, 1) 스타일 코드와 컴포넌트 코드가 아예 다른 위치로 분리되어 있어서 코드 locality가 떨어져 탐색시 불편하고 2) css가 글로벌하기 때문에 class 이름 충돌 등이 발생할 수 있다는 문제가 있습니다.
3. 위보다 약간 더 나은 방식은 `css-loader`와 `style-loader`를 셋업하고, 스타일이 필요한 컴포넌트 파일과 같은 위치에 `.css` 파일을 만들어 css class를 정의한 뒤 `.tsx` 파일에서 `.css` 파일을 임포트하고 `className`으로 클래스를 부여하는 방식이 있습니다. 이 방식은 위의 1)은 해결되었지만 2)가 여전합니다.
4. 문제 2)까지 해결하기 위한 방법으로 CSS Modules가 있는데, 이부분은 좀 더 찾아보시면 되고,
5. 그 외에 CSS-in-JS 라고 해서, 리액트 코드상에서 스타일을 선언해 사용하는 방법들이 있습니다. `emotion` 과 `styled-components`가 이 쪽에서는 가장 유명한 라이브러리인데요, 아마 각 라이브러리별 문서만 한번 살펴봐도 어떤 컨셉일지 대충 이해하실 수 있을겁니다.
6. 최근 패러다임은 Zero-runtime CSS-in-JS 인데요, 이 친구는 위 CSS-in-JS 솔루션들과 비슷하게 js 내지는 ts 코드로 css를 작성하는데 이게 런타임에 해석되어 css로 들어가는게 아닌, 빌드 타임에 해석되어 css 파일로 변환되고 최종 결과물엔 빌드된 css 파일만 삽입되는 형식입니다. React 18로 넘어오면서 Server component가 생기고 그걸 기반으로 툴링 환경이 변화하고 있는데, 그 변화와 연계되어 나타난 현상입니다. 대표적인 라이브러리는 vanilla-extract, panda CSS 등이 있는데, 아직 초창기라서 좀 여러 라이브러리들이 난립하고 있는 상황이긴 합니다.

길게 썼지만 "아무튼 SPA에서 쓰기 좋은 스타일링 방법"을 궁금해 하시는거라면, 위 내용 중 3번과 그 이후의 것들이 실제로 쓰이는 방법이라 생각하시면 될 것 같습니다.

2024-04-01 06:17 UTC, JaegeonJo commented
@limgit 이 말씀해주신 내용입니다. 
기록을 위해 코멘트로 남겨둡니다.

- 특정 component/logic을 모듈화 할때는 over abstraction에 주의하세요. 알맞게 만들어진 모듈은 서로간의 coupling이 느슨합니다.
    - 코드를 작성하다 보면 중복된 코드가 보이고, 이를 없애고 싶은 마음이 들 때가 있습니다. 자연스러운 현상이지만, **의미적 중복**과 **형식적 중복**을 명확히 구분해야 합니다. 전자는 모듈화/추상화를 통해 중복을 제거해야 하지만, 후자의 경우 제거하지 않는 편이 추후 유지보수에 더 도움이 되는 경우가 많습니다.
    - 형식적 중복과 의미적 중복을 구분하기 위한 쉬운 방법 중 하나는 ’이 부분이 변경되었을 때 중복으로 보이는 다른 부분도 똑같은 변경이 일어나야 하는가?’를 생각해보는 것입니다. 답이 ’예’라면 의미적 중복일 가능성이 높고, ’아니오’라면 형식적 중복일 가능성이 높습니다.
    - 형식적 중복의 잘못된 모듈화로 발생하는 대표적인 문제로는 추후 요구되는 스펙 변경에 따른 과한 분기 추가 등이 있습니다.

2024-04-01 11:17 UTC, JaegeonJo commented
VSCode LiveShare를 통한 코드리뷰 진행하였습니다.

2024-04-01 11:17 UTC, merged